name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run_unit_tests:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Run Unit Tests
        run: ./gradlew common:testDebug
      # - name: Publish Test Results
      #   uses: mikepenz/action-junit-report@v5
      #   if: success() || failure()
      #   with:
      #     report_paths: '**/common/build/test-results/testDebugUnitTest/TEST-*.xml'

  run_ui_tests:
    name: Build and UI Test
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run UI Tests
        run: ./gradlew sampleapp:pixel5api34DebugAndroidTest
    # - name: Publish Test Results
    #   uses: mikepenz/action-junit-report@v5
    #   if: success() || failure()
    #   with:
    #     report_paths: 'sampleapp/build/outputs/androidTest-results/managedDevice/debug/pixel5api34/*.xml'
  build_kherkin:
    name: Build Kherkin
    runs-on: ubuntu-latest
    # needs: [run_unit_tests, run_ui_tests]
    # if publish selected
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        run: ./gradlew assembleRelease --stacktrace
        # publish snapshot here?
